import React from 'react'

const Left = ({generate, setGenerate, details, setDetails, genStatus, handleGenerate, filename, setFilename}) => {

    
    const handleChange = (e)=>{
        let name = e.target.name;
        let value = e.target.value;
        let temp = {...details}
        temp[name] = value;
        setDetails(temp)
    }
    return (
        <div>
                <h1 className='text-center sm:w-[500px] mb-5 text-xl sm:text-2xl font-medium text-my-text'>Quick Document Create</h1>
                <div className='text-my-text text-lg sm:text-xl sm:inline'>Generate Details</div>
                <input 
                    type="radio" 
                    name='auto' 
                    value="auto"
                    onChange={(e)=>setGenerate(e.target.value)} 
                    checked={generate == "auto"}
                    className='sm:ml-5 mt-4 sm:mt-0 mr-1 w-7 text-xs sm:text-base'
                    /> <label htmlFor="autogen"> Auto</label>

                <input 
                    type="radio" 
                    name='auto'
                    value="custom"
                    onChange={(e)=>setGenerate(e.target.value)} 
                    checked={generate == "custom"}
                    className='ml-5 mr-1 w-7 text-xs sm:text-base'
                    /> <label htmlFor="autogen"> Custom</label>
                {generate === "auto"
                ?<div className='mt-4 space-y-2'>
                    <div className='bg-yellow-500 uppercase px-2 rounded-md text-white inline'>Selected</div>
                    <div className='inline ml-4 text-my-text'>Auto Generate Content</div>
                    <p className='ml-2 text-my-primary'>Now, Content of the Business Document will be generated by itself ! </p>
                    <table>
                        <tbody>

                        <tr className='flex justify-between w-[300px]'>
                            <td className='py-3  tracking-wide uppercase text-lg mr-3 text-my-primary' >File name</td>
                            <td className='py-3 text-center'>:</td>
                            <td className='py-3'>
                                <input value={filename} className=' placeholder:pl-1 px-1 rounded-md border-2 border-slate-500' name='service_provider_name' onChange={(e)=>setFilename(e.target.value)} type="text" placeholder='without extension'  />
                            </td>

                        </tr>
                        </tbody>
                    </table>
                </div>
                :
                <table className=' mt-5'>
                    
                    <tbody>

                        <tr className='flex justify-between sm:w-[500px]'>
                            <td className='py-3 w-40 tracking-wide uppercase text-sm sm:text-lg mr-3 text-my-primary' >service provider</td>
                            <td className='py-3 text-center'>:</td>
                            <td className='py-3'>
                                <input className='placeholder:pl-1 px-1 rounded-md border-2 border-slate-500' name='service_provider_name' value={details.service_provider_name} onChange={handleChange}  type="text" placeholder='name'  />
                            </td>
                        </tr>
                        <tr className='flex justify-between sm:w-[500px]'>
                            <td className='py-3 w-40 tracking-wide uppercase text-sm sm:text-lg mr-3 text-my-primary' >Client</td>
                            <td className='py-3 text-center'>:</td>
                            <td className='py-3'>
                                <input className='placeholder:pl-1 px-1 rounded-md border-2 border-slate-500' name='client_name' value={details.client_name} onChange={handleChange}  type="text" placeholder='name'  />
                            </td>
                        </tr>

                        <tr className='flex justify-between sm:w-[500px]'>
                            <td className='py-3 w-40 tracking-wide uppercase text-sm sm:text-lg mr-3 text-my-primary' >amount</td>
                            <td className='py-3 text-center'>:</td>
                            <td className='py-3'>
                                <input className='placeholder:pl-1 px-1 rounded-md border-2 border-slate-500' name='amount' value={details.amount} onChange={handleChange} type="number" placeholder='Dollar'  />
                            </td>

                        </tr>
                        <tr className='flex justify-between sm:w-[500px]'>
                            <td className='py-3 w-40 tracking-wide uppercase text-sm sm:text-lg mr-3 text-my-primary' >start date</td>
                            <td className='py-3 text-center'>:</td>
                            <td className='py-3'>
                                <input className='placeholder:pl-1 px-1 rounded-md border-2 border-slate-500' name='start_date' value={details.start_date} onChange={handleChange} type="text"  placeholder='dd-mm-yyyy'  />
                            </td>
                        </tr>

                        <tr className='flex justify-between sm:w-[500px]'>
                            <td className='py-3 w-40 tracking-wide uppercase text-sm sm:text-lg mr-3 text-my-primary' >end date</td>
                            <td className='py-3 text-center'>:</td>
                            <td className='py-3'>
                                <input className='placeholder:pl-1 px-1 rounded-md border-2 border-slate-500' name='end_date' value={details.end_date} onChange={handleChange} type="text" placeholder='dd-mm-yyyy'  />
                            </td>

                        </tr>
                        <tr className='flex justify-between sm:w-[500px]'>
                            <td className='py-3 w-40 tracking-wide uppercase text-sm sm:text-lg mr-3 text-my-primary' >notice days</td>
                            <td className='py-3 text-center'>:</td>
                            <td className='py-3'>
                                <input className='placeholder:pl-1 px-1 rounded-md border-2 border-slate-500' name='notice_days' value={details.notice_days} onChange={handleChange}  type="number" placeholder='days'  />
                            </td>
                        </tr>

                        <tr className='flex justify-between w-[300px]'>
                            <td className='py-3  tracking-wide uppercase text-lg mr-3 text-my-primary' >File name</td>
                            <td className='py-3 text-center'>:</td>
                            <td className='py-3'>
                                <input value={filename} className=' placeholder:pl-1 px-1 rounded-md border-2 border-slate-200' name='service_provider_name' onChange={(e)=>setFilename(e.target.value)} type="text" placeholder='without extension'  />
                            </td>

                        </tr>
                    </tbody>
                </table>
                }
                <button disabled={genStatus} onClick={handleGenerate} className='mt-6 p-2 bg-my-primary text-white rounded-md' >Genterate</button>
            </div>
  )
}

export default Left